import axios, { AxiosRequestConfig } from "axios";
import { Config } from "../Config";

const authInterceptor = (config: AxiosRequestConfig) => {
// const token = localStorage.getItem("authToken");
 const token='eyJhbGciOiJSUzI1NiIsImtpZCI6InByaXZhdGUtc2lnbmluZy1rZXkifQ.eyJzdWIiOiIyMWNkMmQ4Mi0xYmJjLTQzZTktODk4YS1kNWE0NWFiZGVjZWQiLCJuYW1lIjoiQW5kcmVzIiwidXNlck5hbWUiOiJBbmRyZXMiLCJlbWFpbCI6ImFuZHJlc29ybGFuZG9sb3BlekBnbWFpbC5jb20iLCJyb2xlcyI6WyJBZG1pbmlzdHJhdG9yIiwiTGFuZ3VhZ2UgZGV2ZWxvcGVyIiwiTGFuZ3VhZ2UgZGlyZWN0b3IiXSwicGVybWlzc2lvbnMiOlsiYWRtaW46Omxhbmd1YWdlczo6dXBkYXRlIiwiYWRtaW46Omxhbmd1YWdlczo6cXVlcnkiLCJhZG1pbjo6bGFuZ3VhZ2VzOjpkZWxldGUiLCJhZG1pbjo6bW9kZWxzOjp1cGRhdGUiLCJhZG1pbjo6bW9kZWxzOjpkZWxldGUiLCJhZG1pbjo6bW9kZWxzOjpxdWVyeSIsImFkbWluOjpwcm9qZWN0czo6dXBkYXRlIiwiYWRtaW46OnByb2plY3RzOjpxdWVyeSIsImFkbWluOjpwcm9qZWN0czo6ZGVsZXRlIiwidXNlcnM6OmRlbGV0ZSIsIm1pY3JvLXNlcnZpY2VzOjp1cGRhdGUiLCJtaWNyby1zZXJ2aWNlczo6cXVlcnkiLCJtZXRyaWNzOjpxdWVyeSIsInVzZXJzOjp1cGRhdGUiLCJ1c2Vyczo6cXVlcnkiLCJwZXJtaXNzaW9uczo6dXBkYXRlIiwicGVybWlzc2lvbnM6OnF1ZXJ5IiwicGVybWlzc2lvbnM6OmRlbGV0ZSIsInBlcm1pc3Npb25zOjpjcmVhdGUiLCJyb2xlczo6dXBkYXRlIiwicm9sZXM6OnF1ZXJ5Iiwicm9sZXM6OmRlbGV0ZSIsInJvbGVzOjpjcmVhdGUiLCJsYW5ndWFnZXM6OmRlbGV0ZSIsImxhbmd1YWdlczo6dXBkYXRlIiwibGFuZ3VhZ2VzOjpxdWVyeSIsImxhbmd1YWdlczo6Y3JlYXRlIiwibXktYWNjb3VudDo6dXBkYXRlIiwibXktYWNjb3VudDo6cXVlcnkiLCJDcmVhdGUgcHJvZHVjdCBsaW5lcyIsIkNyZWF0ZSBsYW5ndWFnZXMiLCJDcmVhdGUgbGFuZ3VhZ2VzIiwiQ3JlYXRlIHByb2R1Y3QgbGluZXMiLCJBcHByb3ZlIGxhbmd1YWdlcyJdLCJpYXQiOjE3NTYzMDIxMDAsImV4cCI6MTc1NjczNDEwMCwiYXVkIjoibG9jYWxob3N0In0.Eg7NeSGmdURYgerBo2AOIp7-9V8n9Rls-gplThhHDGLHh3uibtAXN7zKrhe13MWrhC5Gpg-q6m9H3veeu3HPIqrGMfmDV62bVLrNrD1N2U05QUhfv66y47zOj_4kuuuZVEjmOgx1PCgepE4pqoSHVcAJm3OJNeiSIbe-917HS4d91j4Nal4pEuNvujwoctjy2UfouLo0sORZbf9v8wA0lkmyH1WWleMwZa3rhMsvlgZiU-9btkw6ZslACF3TZHnu8MB-ZH2z6oyz90iY-Zl4WZZaefZlff6E0k6Msa0OMo2BFUNgfPtQ3Nb3lIxD7I3WfXkO2E8EcHYi3W6XGGnD0US2XvcwJTJxIu-XCEK1_YP4ph51RWVXdwu2c1ChZFUQ-clEnomJGyLZD1iu0-_062HqXLiwsGkefRUaWe5EuHX4Q_FEaYivwCgZQIMw4bdXH4O5boMrx5S3m2Rgu5DDphv9BBO1DRgfTiI015qXGrpOYBvSCDksOdgLw8_UB5mhScBQk_4mPN9GzUtJ7uOf6Puf__zdhyd8zoRSZGxHBKrkakP8-KegnPFk6PeQ-gguxGZy4c84ZBSwkbIAsk7g2Ou7H7qW15bpRpdrJYFuw3pGN6V5bNHV6a8FB41jy1HBFY5RlxDdjfWVTC-_rqrurXyXxE5cxn4uLxYrDnwLVwo';  //todo: comentariar al publicar
  if (token) {
    config.headers.Authorization = `Bearer ${token}`;
  }
  return config;
};

export const ADMIN_CLIENT = axios.create({
  baseURL: Config.SERVICES.urlBackEndAdmin,
  timeout: 30000,
  withCredentials: true,
});

ADMIN_CLIENT.interceptors.request.use(authInterceptor);

export const LANGUAGES_CLIENT = axios.create({
  baseURL: Config.SERVICES.urlBackEndLanguage,
  timeout: 30000,
  withCredentials: true,
});

LANGUAGES_CLIENT.interceptors.request.use(authInterceptor);

export const PROJECTS_CLIENT = axios.create({
  baseURL: Config.SERVICES.urlBackEndProjectPersistence,
  timeout: 30000,
  withCredentials: true,
});

PROJECTS_CLIENT.interceptors.request.use(authInterceptor);
