import axios, { AxiosRequestConfig } from "axios";
import { Config } from "../Config";

const authInterceptor = (config: AxiosRequestConfig) => {
// const token = localStorage.getItem("authToken");
 const token='eyJhbGciOiJSUzI1NiIsImtpZCI6InByaXZhdGUtc2lnbmluZy1rZXkifQ.eyJzdWIiOiIyMWNkMmQ4Mi0xYmJjLTQzZTktODk4YS1kNWE0NWFiZGVjZWQiLCJuYW1lIjoiQW5kcmVzIiwidXNlck5hbWUiOiJBbmRyZXMiLCJlbWFpbCI6ImFuZHJlc29ybGFuZG9sb3BlekBnbWFpbC5jb20iLCJyb2xlcyI6WyJBZG1pbmlzdHJhdG9yIiwiTGFuZ3VhZ2UgZGV2ZWxvcGVyIiwiTGFuZ3VhZ2UgZGlyZWN0b3IiXSwicGVybWlzc2lvbnMiOlsiYWRtaW46Omxhbmd1YWdlczo6dXBkYXRlIiwiYWRtaW46Omxhbmd1YWdlczo6cXVlcnkiLCJhZG1pbjo6bGFuZ3VhZ2VzOjpkZWxldGUiLCJhZG1pbjo6bW9kZWxzOjp1cGRhdGUiLCJhZG1pbjo6bW9kZWxzOjpkZWxldGUiLCJhZG1pbjo6bW9kZWxzOjpxdWVyeSIsImFkbWluOjpwcm9qZWN0czo6dXBkYXRlIiwiYWRtaW46OnByb2plY3RzOjpxdWVyeSIsImFkbWluOjpwcm9qZWN0czo6ZGVsZXRlIiwidXNlcnM6OmRlbGV0ZSIsIm1pY3JvLXNlcnZpY2VzOjp1cGRhdGUiLCJtaWNyby1zZXJ2aWNlczo6cXVlcnkiLCJtZXRyaWNzOjpxdWVyeSIsInVzZXJzOjp1cGRhdGUiLCJ1c2Vyczo6cXVlcnkiLCJwZXJtaXNzaW9uczo6dXBkYXRlIiwicGVybWlzc2lvbnM6OnF1ZXJ5IiwicGVybWlzc2lvbnM6OmRlbGV0ZSIsInBlcm1pc3Npb25zOjpjcmVhdGUiLCJyb2xlczo6dXBkYXRlIiwicm9sZXM6OnF1ZXJ5Iiwicm9sZXM6OmRlbGV0ZSIsInJvbGVzOjpjcmVhdGUiLCJsYW5ndWFnZXM6OmRlbGV0ZSIsImxhbmd1YWdlczo6dXBkYXRlIiwibGFuZ3VhZ2VzOjpxdWVyeSIsImxhbmd1YWdlczo6Y3JlYXRlIiwibXktYWNjb3VudDo6dXBkYXRlIiwibXktYWNjb3VudDo6cXVlcnkiLCJDcmVhdGUgcHJvZHVjdCBsaW5lcyIsIkNyZWF0ZSBsYW5ndWFnZXMiLCJDcmVhdGUgbGFuZ3VhZ2VzIiwiQ3JlYXRlIHByb2R1Y3QgbGluZXMiLCJBcHByb3ZlIGxhbmd1YWdlcyJdLCJpYXQiOjE3NTc1MDg1MzAsImV4cCI6MTc1Nzk0MDUzMCwiYXVkIjoiYXBwLnZhcmlhbW9zLmNvbSJ9.N2qV1pS8UWilB54WA46w13_1p5e05n7IZIuYbyB2veDk44Y2BsohKlM4j_0FbqHLNor5Xb43OcaKVQwy-5U8k8XU35LOWlmX1XavjM_3Ecu1AW48hXrXJBh-beH-l79lfyXWdPDIVuJhMsTEa6uVWP4wHfxd8YWT97JT8A4FZg9Dmwyb8wJlqIfio2AiFM9EXcgxQ4ShNQqZ9x60Y8dY5Uikr1DHR3gW56sMFj3VnM4oXAKZaKD3nq2qPGLDY4rrEApx8ZL_jJFjsehl2Rlnxyov-BO6f0HzGwU1jfonzKlrUi_l3hv24Y6q0sT5lk_HKwTdvgtB0mFKofIBaDXucTRk1qVms-Hlbkin3Ne7fQ0wwjVGuPtt4Llo_QaQr7S5liN6SwRqFaLCjwwNZxHD0Ls5f7Sm7mUK3Xjhh1otzK9gf-sH1JF8NM63FJt6eB4YYs6WESyK3eDvcP6pencCbsQNIzNDTCkPR6M68Y4CVXI6xOcQW-Ld4-MLOcYOUanmoNQiz4RNW9LwDmtopo362PmNhphlFZlW2Xapw_0qoy42Cjq1yLXYUCmYtxCbjzv_a_UZPdprh2bJEY0bk_ro7Def9iDFx8i0WoclqFOXieMKYKe52r_XiC0d7_dJ0ZthO7KHBMVUe8Sz7AvTK4T--qBE4REbIjwqAzjazNydkLc';  //todo: comentariar al publicar
  if (token) {
    config.headers.Authorization = `Bearer ${token}`;
  }
  return config;
};

export const ADMIN_CLIENT = axios.create({
  baseURL: Config.SERVICES.urlBackEndAdmin,
  timeout: 30000,
  withCredentials: true,
});

ADMIN_CLIENT.interceptors.request.use(authInterceptor);

export const LANGUAGES_CLIENT = axios.create({
  baseURL: Config.SERVICES.urlBackEndLanguage,
  timeout: 30000,
  withCredentials: true,
});

LANGUAGES_CLIENT.interceptors.request.use(authInterceptor);

export const PROJECTS_CLIENT = axios.create({
  baseURL: Config.SERVICES.urlBackEndProjectPersistence,
  timeout: 30000,
  withCredentials: true,
});

PROJECTS_CLIENT.interceptors.request.use(authInterceptor);
