import axios, { AxiosRequestConfig } from "axios";
import { Config } from "../Config";

const authInterceptor = (config: AxiosRequestConfig) => {
 const token = localStorage.getItem("authToken");
  //const token='eyJhbGciOiJSUzI1NiIsImtpZCI6InByaXZhdGUtc2lnbmluZy1rZXkifQ.eyJzdWIiOiIyMWNkMmQ4Mi0xYmJjLTQzZTktODk4YS1kNWE0NWFiZGVjZWQiLCJuYW1lIjoiQW5kcmVzIiwidXNlck5hbWUiOiJBbmRyZXMiLCJlbWFpbCI6ImFuZHJlc29ybGFuZG9sb3BlekBnbWFpbC5jb20iLCJyb2xlcyI6WyJBZG1pbmlzdHJhdG9yIiwiTGFuZ3VhZ2UgZGV2ZWxvcGVyIiwiTGFuZ3VhZ2UgZGlyZWN0b3IiXSwicGVybWlzc2lvbnMiOlsiYWRtaW46Omxhbmd1YWdlczo6dXBkYXRlIiwiYWRtaW46Omxhbmd1YWdlczo6cXVlcnkiLCJhZG1pbjo6bGFuZ3VhZ2VzOjpkZWxldGUiLCJhZG1pbjo6bW9kZWxzOjp1cGRhdGUiLCJhZG1pbjo6bW9kZWxzOjpkZWxldGUiLCJhZG1pbjo6bW9kZWxzOjpxdWVyeSIsImFkbWluOjpwcm9qZWN0czo6dXBkYXRlIiwiYWRtaW46OnByb2plY3RzOjpxdWVyeSIsImFkbWluOjpwcm9qZWN0czo6ZGVsZXRlIiwidXNlcnM6OmRlbGV0ZSIsIm1pY3JvLXNlcnZpY2VzOjp1cGRhdGUiLCJtaWNyby1zZXJ2aWNlczo6cXVlcnkiLCJtZXRyaWNzOjpxdWVyeSIsInVzZXJzOjp1cGRhdGUiLCJ1c2Vyczo6cXVlcnkiLCJwZXJtaXNzaW9uczo6dXBkYXRlIiwicGVybWlzc2lvbnM6OnF1ZXJ5IiwicGVybWlzc2lvbnM6OmRlbGV0ZSIsInBlcm1pc3Npb25zOjpjcmVhdGUiLCJyb2xlczo6dXBkYXRlIiwicm9sZXM6OnF1ZXJ5Iiwicm9sZXM6OmRlbGV0ZSIsInJvbGVzOjpjcmVhdGUiLCJsYW5ndWFnZXM6OmRlbGV0ZSIsImxhbmd1YWdlczo6dXBkYXRlIiwibGFuZ3VhZ2VzOjpxdWVyeSIsImxhbmd1YWdlczo6Y3JlYXRlIiwibXktYWNjb3VudDo6dXBkYXRlIiwibXktYWNjb3VudDo6cXVlcnkiLCJDcmVhdGUgcHJvZHVjdCBsaW5lcyIsIkNyZWF0ZSBsYW5ndWFnZXMiLCJDcmVhdGUgbGFuZ3VhZ2VzIiwiQ3JlYXRlIHByb2R1Y3QgbGluZXMiLCJBcHByb3ZlIGxhbmd1YWdlcyJdLCJpYXQiOjE3NjI3NzU1MTgsImV4cCI6MTc2MzIwNzUxOCwiYXVkIjoiYXBwLnZhcmlhbW9zLmNvbSJ9.HKOT3UuwyAfqaSECzHruJWfM3sGmWpMWRw9xfr1p53nAB8lWGt97mxAcMsru_fPY908NA331vybvPJDylCN4Lnfdl-xKnBh9IZvBSgi3tpsbwBZ6wkZ7RXLsEapXerv570oZW5-YubnsLIc2eU3lz9k6d-dOvOUzr-0wUV6rVlsqV_ArBGcVO4l9JG9h32cTG-MHNOwb4L9Wj9zU4ER5bHSeYJEIXOYj0OKykAX0e7ra3maEXNGYO_5-WgK30z2chSxKcrxFLCTzfJO54TOOKbH2_8RTEffB6H5FGKbnKPenBChBKJqX636T6Sdz9cj50Ewz0KfETCoT7OhlKeHTjyJ4G9_otizDq3USsVE7pGWL-mMHDxxb1YyGhMsKjxanpzwNQ4xZzkcTD4bXWnP_RWjJIXwYiF1MYqwuXslfQpa_9722usxbRUl_xGd_KR9CcRy5A3wRFilWZH_ksuSYdcxIJhPc9hC63QC3XYj1LN9_e0JZ5dZVdAFisUdIEKsknTMkkxTuk2XZKSzB_5moFtwsYUWHMdjpgb7T0vil5IRwiQ8dskVG6sF_SY7l2D90rpX7n13Rw_j-b0LD2fuwa8Bmw-_G_Xu7AWtSdfbJBKc_4LftxkgpbPNS62zZH0ToswCw4PvrVsnwMa7NxoyDMtEpYUch9XnKwSUrL4LvV5Y';  //todo: comentariar al publicar
  if (token) {
    config.headers.Authorization = `Bearer ${token}`;
  }
  return config;
};

export const ADMIN_CLIENT = axios.create({
  baseURL: Config.SERVICES.urlBackEndAdmin,
  timeout: 30000,
  withCredentials: true,
});

ADMIN_CLIENT.interceptors.request.use(authInterceptor);

export const LANGUAGES_CLIENT = axios.create({
  baseURL: Config.SERVICES.urlBackEndLanguage,
  timeout: 30000,
  withCredentials: true,
});

LANGUAGES_CLIENT.interceptors.request.use(authInterceptor);

export const PROJECTS_CLIENT = axios.create({
  baseURL: Config.SERVICES.urlBackEndProjectPersistence,
  timeout: 30000,
  withCredentials: true,
});

PROJECTS_CLIENT.interceptors.request.use(authInterceptor);
