import {
  composeUvlSources,
  type UvlSubmodelSources,
} from "./uvlComposition";
import type {
  UvlDiagnostic,
  UvlDocument,
  UvlExpression,
  UvlFeature,
  UvlGroup,
  UvlReference,
} from "./uvlParser";

/** Solver engines exposed by the UVL editor. */
export type UvlSolverType = "sat" | "bdd";

export type UvlSolverStatus = "sat" | "unsat" | "unknown" | "error";

export type UvlSolverAnalysisResult = {
  solver: UvlSolverType;
  status: UvlSolverStatus;
  title: string;
  summary: string;
  details: string[];
  /** A satisfying feature assignment, when one was found. */
  model?: Record<string, boolean>;
  /** Number of satisfying feature assignments for BDD analysis. */
  modelCount?: number;
  featureCount?: number;
  clauseCount?: number;
  bddNodeCount?: number;
  elapsedMs?: number;
};

export type UvlSolverOptions = {
  /** Maximum wall-clock time for one analysis. */
  maxMillis?: number;
  /** Maximum DPLL decisions. */
  maxDecisions?: number;
  /** Maximum SAT variables generated by the Tseitin encoding. */
  maxSatVariables?: number;
  /** Maximum generated SAT clauses. */
  maxSatClauses?: number;
  /** Maximum reduced BDD nodes. */
  maxBddNodes?: number;
};

type Formula =
  | { kind: "constant"; value: boolean }
  | { kind: "variable"; variable: number }
  | { kind: "not"; operand: Formula }
  | { kind: "and" | "or"; operands: Formula[] }
  | { kind: "cardinality"; variables: number[]; min: number; max: number; parent?: number };

type FeatureEntry = {
  feature: UvlFeature;
  variable: number;
  displayName: string;
};

type CompileContext = {
  featureByName: Map<string, FeatureEntry>;
  featureEntries: FeatureEntry[];
  unsupported: string[];
  unsupportedKeys: Set<string>;
};

type CompileResult = {
  formulas: Formula[];
  featureEntries: FeatureEntry[];
  unsupported: string[];
  topLevelConstraintCount: number;
};

type SatResult = {
  status: "sat" | "unsat" | "unknown";
  assignment?: Int8Array;
  decisions: number;
  propagations: number;
  conflicts: number;
  elapsedMs: number;
  reason?: string;
};

type BddResult = {
  status: "sat" | "unsat" | "unknown";
  root: number;
  model?: Record<string, boolean>;
  modelCount?: number;
  nodeCount: number;
  elapsedMs: number;
  reason?: string;
};

const DEFAULT_OPTIONS: Required<UvlSolverOptions> = {
  maxMillis: 1500,
  maxDecisions: 100000,
  maxSatVariables: 5000,
  maxSatClauses: 50000,
  maxBddNodes: 50000,
};

function canonicalName(value: string): string {
  return String(value || "").trim().toLowerCase();
}

function locationText(diagnostic: Pick<UvlDiagnostic, "location">): string {
  return `line ${diagnostic.location.line}, column ${diagnostic.location.column}`;
}

function addUnsupported(context: CompileContext, message: string, expression?: UvlExpression): void {
  const location = expression ? ` (${expression.location.line}:${expression.location.column})` : "";
  const item = `${message}${location}`;
  const key = item.toLowerCase();
  if (!context.unsupportedKeys.has(key)) {
    context.unsupportedKeys.add(key);
    context.unsupported.push(item);
  }
}

function constant(value: boolean): Formula {
  return { kind: "constant", value };
}

function formulaNot(operand: Formula): Formula {
  if (operand.kind === "constant") return constant(!operand.value);
  if (operand.kind === "not") return operand.operand;
  return { kind: "not", operand };
}

function formulaAnd(...operands: Formula[]): Formula {
  const flattened: Formula[] = [];
  operands.forEach((operand) => {
    if (operand.kind === "and") flattened.push(...operand.operands);
    else flattened.push(operand);
  });
  if (flattened.some((operand) => operand.kind === "constant" && !operand.value)) return constant(false);
  const filtered = flattened.filter((operand) => !(operand.kind === "constant" && operand.value));
  if (!filtered.length) return constant(true);
  if (filtered.length === 1) return filtered[0];
  return { kind: "and", operands: filtered };
}

function formulaOr(...operands: Formula[]): Formula {
  const flattened: Formula[] = [];
  operands.forEach((operand) => {
    if (operand.kind === "or") flattened.push(...operand.operands);
    else flattened.push(operand);
  });
  if (flattened.some((operand) => operand.kind === "constant" && operand.value)) return constant(true);
  const filtered = flattened.filter((operand) => !(operand.kind === "constant" && !operand.value));
  if (!filtered.length) return constant(false);
  if (filtered.length === 1) return filtered[0];
  return { kind: "or", operands: filtered };
}

function formulaImplies(left: Formula, right: Formula): Formula {
  return formulaOr(formulaNot(left), right);
}

function formulaEquivalent(left: Formula, right: Formula): Formula {
  return formulaAnd(formulaImplies(left, right), formulaImplies(right, left));
}

function expressionReferences(expression: UvlExpression | undefined, callback: (reference: UvlReference) => void): void {
  if (!expression) return;
  if (expression.kind === "reference") callback(expression.reference);
  else if (expression.kind === "aggregate") expression.arguments.forEach(callback);
  else if (expression.kind === "unary") expressionReferences(expression.operand, callback);
  else if (expression.kind === "binary") {
    expressionReferences(expression.left, callback);
    expressionReferences(expression.right, callback);
  } else if (expression.kind === "parenthesized") expressionReferences(expression.expression, callback);
}

function collectFeatures(root: UvlFeature | undefined): FeatureEntry[] {
  const entries: FeatureEntry[] = [];
  const seen = new Set<UvlFeature>();
  const visit = (feature: UvlFeature): void => {
    if (seen.has(feature)) return;
    seen.add(feature);
    entries.push({ feature, variable: entries.length, displayName: feature.name });
    feature.groups.forEach((group) => group.features.forEach(visit));
  };
  if (root) visit(root);
  return entries;
}

function makeFeatureMap(entries: FeatureEntry[]): Map<string, FeatureEntry> {
  const result = new Map<string, FeatureEntry>();
  entries.forEach((entry) => {
    const names = [entry.feature.name, entry.feature.reference.name];
    names.forEach((name) => {
      const key = canonicalName(name);
      if (key && !result.has(key)) result.set(key, entry);
    });
  });
  return result;
}

function resolveFeature(reference: UvlReference, context: CompileContext): FeatureEntry | undefined {
  const exact = context.featureByName.get(canonicalName(reference.name));
  if (exact) return exact;

  // UVL permits a short reference when the suffix is unambiguous.  This is
  // especially useful for imported names such as `Catalog.Web.Editor`.
  const key = canonicalName(reference.name);
  const suffixMatches = context.featureEntries.filter((entry) => {
    const entryName = canonicalName(entry.feature.name);
    return entryName === key || entryName.endsWith(`.${key}`);
  });
  return suffixMatches.length === 1 ? suffixMatches[0] : undefined;
}

type LiteralValue = { kind: "boolean" | "number" | "string"; value: boolean | number | string };

function evaluateLiteral(expression: UvlExpression | undefined): LiteralValue | undefined {
  if (!expression) return undefined;
  if (expression.kind === "boolean") return { kind: "boolean", value: expression.value };
  if (expression.kind === "number") return { kind: "number", value: expression.value };
  if (expression.kind === "string") return { kind: "string", value: expression.value };
  if (expression.kind === "parenthesized") return evaluateLiteral(expression.expression);
  if (expression.kind === "unary") {
    const operand = evaluateLiteral(expression.operand);
    if (!operand) return undefined;
    if (expression.operator === "!" && operand.kind === "boolean") return { kind: "boolean", value: !operand.value };
    if (expression.operator === "-" && operand.kind === "number") return { kind: "number", value: -operand.value };
    return undefined;
  }
  if (expression.kind !== "binary") return undefined;
  const left = evaluateLiteral(expression.left);
  const right = evaluateLiteral(expression.right);
  if (!left || !right) return undefined;
  if (["&", "|", "=>", "<=>"].includes(expression.operator)) {
    if (left.kind !== "boolean" || right.kind !== "boolean") return undefined;
    if (expression.operator === "&") return { kind: "boolean", value: left.value && right.value };
    if (expression.operator === "|") return { kind: "boolean", value: left.value || right.value };
    if (expression.operator === "=>") return { kind: "boolean", value: !left.value || right.value };
    return { kind: "boolean", value: left.value === right.value };
  }
  if (["+", "-", "*", "/"].includes(expression.operator)) {
    if (left.kind !== "number" || right.kind !== "number") return undefined;
    const leftNumber = left.value as number;
    const rightNumber = right.value as number;
    if (expression.operator === "+") return { kind: "number", value: leftNumber + rightNumber };
    if (expression.operator === "-") return { kind: "number", value: leftNumber - rightNumber };
    if (expression.operator === "*") return { kind: "number", value: leftNumber * rightNumber };
    if (right.value === 0) return undefined;
    return { kind: "number", value: leftNumber / rightNumber };
  }
  if (!["==", "!=", "<", ">", "<=", ">="].includes(expression.operator)) return undefined;
  if (left.kind !== right.kind && !(left.kind === "number" && right.kind === "number")) return undefined;
  if (expression.operator === "==") return { kind: "boolean", value: left.value === right.value };
  if (expression.operator === "!=") return { kind: "boolean", value: left.value !== right.value };
  if (typeof left.value !== "number" || typeof right.value !== "number") return undefined;
  if (expression.operator === "<") return { kind: "boolean", value: left.value < right.value };
  if (expression.operator === ">") return { kind: "boolean", value: left.value > right.value };
  if (expression.operator === "<=") return { kind: "boolean", value: left.value <= right.value };
  return { kind: "boolean", value: left.value >= right.value };
}

function compileBooleanExpression(expression: UvlExpression | undefined, context: CompileContext): Formula | null {
  if (!expression) return null;
  const literal = evaluateLiteral(expression);
  if (literal?.kind === "boolean") return constant(literal.value as boolean);

  if (expression.kind === "reference") {
    const feature = resolveFeature(expression.reference, context);
    if (!feature) {
      addUnsupported(context, `Unknown Boolean reference '${expression.reference.name}'.`, expression);
      return null;
    }
    return { kind: "variable", variable: feature.variable };
  }
  if (expression.kind === "parenthesized") return compileBooleanExpression(expression.expression, context);
  if (expression.kind === "unary") {
    if (expression.operator !== "!") {
      addUnsupported(context, "Arithmetic unary operators are not propositional.", expression);
      return null;
    }
    const operand = compileBooleanExpression(expression.operand, context);
    return operand ? formulaNot(operand) : null;
  }
  if (expression.kind === "aggregate") {
    addUnsupported(context, `Aggregate '${expression.function}' requires typed UVL semantics.`, expression);
    return null;
  }
  if (expression.kind !== "binary") {
    addUnsupported(context, "The expression cannot be translated to a Boolean formula.", expression);
    return null;
  }

  if (["&", "|", "=>", "<=>"].includes(expression.operator)) {
    const left = compileBooleanExpression(expression.left, context);
    const right = compileBooleanExpression(expression.right, context);
    if (!left || !right) return null;
    if (expression.operator === "&") return formulaAnd(left, right);
    if (expression.operator === "|") return formulaOr(left, right);
    if (expression.operator === "=>") return formulaImplies(left, right);
    return formulaEquivalent(left, right);
  }

  if (["==", "!="].includes(expression.operator)) {
    const leftLiteral = evaluateLiteral(expression.left);
    const rightLiteral = evaluateLiteral(expression.right);
    const left = compileBooleanExpression(expression.left, context);
    const right = compileBooleanExpression(expression.right, context);
    if (left && right && (!leftLiteral || leftLiteral.kind === "boolean") && (!rightLiteral || rightLiteral.kind === "boolean")) {
      const equivalent = formulaEquivalent(left, right);
      return expression.operator === "==" ? equivalent : formulaNot(equivalent);
    }
    if (left && rightLiteral?.kind === "boolean") {
      const equivalent = rightLiteral.value ? left : formulaNot(left);
      return expression.operator === "==" ? equivalent : formulaNot(equivalent);
    }
    if (right && leftLiteral?.kind === "boolean") {
      const equivalent = leftLiteral.value ? right : formulaNot(right);
      return expression.operator === "==" ? equivalent : formulaNot(equivalent);
    }
    addUnsupported(context, `Comparison '${expression.operator}' is not Boolean-only.`, expression);
    return null;
  }

  if (["<", ">", "<=", ">=", "+", "-", "*", "/"].includes(expression.operator)) {
    addUnsupported(context, `Operator '${expression.operator}' requires typed or arithmetic semantics.`, expression);
    return null;
  }
  addUnsupported(context, `Operator '${expression.operator}' is not supported by the propositional backend.`, expression);
  return null;
}

function compileAttributes(feature: UvlFeature, context: CompileContext): Formula[] {
  const formulas: Formula[] = [];
  feature.attributes.forEach((attribute) => {
    const key = canonicalName(attribute.key);
    // `abstract` is a UVL modifier represented by the parser as a valueless
    // attribute.  It does not constrain feature selection.
    if (key === "abstract" && !attribute.value && !attribute.constraint && !attribute.constraints) return;
    if (!attribute.value && !attribute.constraint && !attribute.constraints) {
      addUnsupported(context, `Valueless attribute '${attribute.key}' is not a recognized UVL modifier.`);
    }
    if (attribute.value) {
      if (attribute.value.kind !== "boolean") {
        addUnsupported(context, `Attribute '${attribute.key}' has a non-Boolean value and was not encoded.`);
      }
      // Boolean attribute values are metadata unless referenced by a typed
      // constraint; the parser keeps their value available to the editor but
      // they do not create a feature-selection variable.
    }
    if (attribute.constraint) {
      const formula = compileBooleanExpression(attribute.constraint, context);
      if (formula) formulas.push(formula);
    }
    attribute.constraints?.forEach((constraint) => {
      const formula = compileBooleanExpression(constraint, context);
      if (formula) formulas.push(formula);
    });
  });
  return formulas;
}

function compileGroup(parent: FeatureEntry, group: UvlGroup, context: CompileContext, formulas: Formula[]): void {
  const children = group.features
    .map((feature) => context.featureByName.get(canonicalName(feature.name)))
    .filter((entry): entry is FeatureEntry => !!entry);

  group.features.forEach((feature) => {
    if (!context.featureByName.has(canonicalName(feature.name))) {
      addUnsupported(context, `Feature '${feature.name}' could not be linked to its parent group.`);
    }
  });

  children.forEach((child) => {
    // A selected child always requires its parent, regardless of group kind.
    formulas.push(formulaImplies({ kind: "variable", variable: child.variable }, { kind: "variable", variable: parent.variable }));
    compileFeature(child, context, formulas);
  });

  if (group.kind === "mandatory") {
    children.forEach((child) => {
      formulas.push(formulaImplies({ kind: "variable", variable: parent.variable }, { kind: "variable", variable: child.variable }));
    });
    return;
  }
  if (group.kind === "optional") return;

  const cardinality = group.cardinality || {
    min: group.kind === "alternative" ? 1 : 1,
    max: group.kind === "alternative" ? 1 : children.length,
  };
  formulas.push({
    kind: "cardinality",
    variables: children.map((child) => child.variable),
    min: cardinality.min,
    max: cardinality.max === "*" ? children.length : cardinality.max,
    parent: parent.variable,
  });
}

function compileFeature(entry: FeatureEntry, context: CompileContext, formulas: Formula[]): void {
  const feature = entry.feature;
  if (feature.featureType && feature.featureType !== "Boolean") {
    addUnsupported(context, `Feature '${feature.name}' has type '${feature.featureType}', which is outside propositional SAT/BDD semantics.`);
  }
  if (feature.cardinality) {
    addUnsupported(context, `Feature '${feature.name}' uses feature cardinality and requires arithmetic semantics.`);
  }
  formulas.push(...compileAttributes(feature, context));
  feature.groups.forEach((group) => compileGroup(entry, group, context, formulas));
}

function compileDocument(document: UvlDocument): CompileResult {
  const featureEntries = collectFeatures(document.root);
  const context: CompileContext = {
    featureEntries,
    featureByName: makeFeatureMap(featureEntries),
    unsupported: [],
    unsupportedKeys: new Set<string>(),
  };
  const formulas: Formula[] = [];
  if (!document.root) {
    addUnsupported(context, "The UVL document has no root feature.");
  } else {
    formulas.push({ kind: "variable", variable: featureEntries[0].variable });
    compileFeature(featureEntries[0], context, formulas);
  }

  let topLevelConstraintCount = 0;
  document.constraints.forEach((constraint) => {
    if (!constraint.expression) return;
    topLevelConstraintCount++;
    const formula = compileBooleanExpression(constraint.expression, context);
    if (formula) formulas.push(formula);
  });

  // Keep diagnostics for references that occur in attribute values visible;
  // values themselves are intentionally not treated as feature variables.
  featureEntries.forEach((entry) => entry.feature.attributes.forEach((attribute) => {
    expressionReferences(attribute.constraint, (reference) => {
      if (!resolveFeature(reference, context)) addUnsupported(context, `Unknown Boolean reference '${reference.name}'.`, attribute.constraint);
    });
    attribute.constraints?.forEach((constraint) => expressionReferences(constraint, (reference) => {
      if (!resolveFeature(reference, context)) addUnsupported(context, `Unknown Boolean reference '${reference.name}'.`, constraint);
    }));
  }));

  return { formulas, featureEntries, unsupported: context.unsupported, topLevelConstraintCount };
}

function formulaToCnf(formulas: Formula[], featureEntries: FeatureEntry[], options: Required<UvlSolverOptions>): {
  clauses: number[][];
  variableCount: number;
  featureVariableCount: number;
  auxVariableCount: number;
  reason?: string;
} {
  const builder = new CnfBuilder(featureEntries.length, options.maxSatVariables, options.maxSatClauses);
  formulas.forEach((formula) => {
    if (formula.kind === "cardinality") {
      builder.addCardinality(
        formula.variables.map((variable) => variable + 1),
        formula.min,
        formula.max,
        formula.parent === undefined ? undefined : formula.parent + 1
      );
      return;
    }
    const literal = builder.encode(formula);
    builder.addClause([literal]);
  });
  return {
    clauses: builder.clauses,
    variableCount: builder.variableCount,
    featureVariableCount: featureEntries.length,
    auxVariableCount: Math.max(0, builder.variableCount - featureEntries.length),
    reason: builder.reason,
  };
}

class CnfBuilder {
  readonly clauses: number[][] = [];
  variableCount: number;
  reason?: string;
  private readonly maxVariables: number;
  private readonly maxClauses: number;

  constructor(featureVariableCount: number, maxVariables: number, maxClauses: number) {
    this.variableCount = featureVariableCount;
    this.maxVariables = maxVariables;
    this.maxClauses = maxClauses;
    if (featureVariableCount > maxVariables) this.reason = `SAT variable limit (${maxVariables}) exceeded by feature variables.`;
  }

  newAuxiliary(): number {
    if (this.reason) return Math.max(1, this.variableCount);
    if (this.variableCount >= this.maxVariables) {
      this.reason = `SAT variable limit (${this.maxVariables}) exceeded.`;
      return Math.max(1, this.variableCount);
    }
    this.variableCount++;
    return this.variableCount;
  }

  addClause(rawLiterals: number[]): void {
    if (this.reason) return;
    const literals = Array.from(new Set(rawLiterals.filter((literal) => literal !== 0)));
    const set = new Set(literals);
    if (literals.some((literal) => set.has(-literal))) return;
    if (this.clauses.length >= this.maxClauses) {
      this.reason = `SAT clause limit (${this.maxClauses}) exceeded.`;
      return;
    }
    this.clauses.push(literals);
  }

  encode(formula: Formula): number {
    if (formula.kind === "constant") {
      const variable = this.newAuxiliary();
      this.addClause([formula.value ? variable : -variable]);
      return variable;
    }
    if (formula.kind === "variable") return formula.variable + 1;
    if (formula.kind === "not") return -this.encode(formula.operand);
    if (formula.kind === "cardinality") {
      // Cardinality nodes are emitted as direct constraints by the caller.
      // Encoding one as a fresh true literal would be unsound, so fail closed.
      this.reason = "Nested cardinality expression cannot be encoded as a single SAT literal.";
      return this.newAuxiliary();
    }
    const operands = formula.operands.map((operand) => this.encode(operand));
    if (!operands.length) {
      const variable = this.newAuxiliary();
      this.addClause([formula.kind === "and" ? variable : -variable]);
      return variable;
    }
    if (operands.length === 1) return operands[0];
    const variable = this.newAuxiliary();
    if (formula.kind === "and") {
      operands.forEach((operand) => this.addClause([-variable, operand]));
      this.addClause([variable, ...operands.map((operand) => -operand)]);
    } else {
      operands.forEach((operand) => this.addClause([variable, -operand]));
      this.addClause([-variable, ...operands]);
    }
    return variable;
  }

  addCardinality(oneBasedVariables: number[], min: number, max: number, parent?: number): void {
    const variables = Array.from(new Set(oneBasedVariables.filter((variable) => variable > 0)));
    if (min < 0 || max < min || min > variables.length) {
      this.addClause([]);
      return;
    }
    const boundedMax = Math.min(max, variables.length);
    if (boundedMax < variables.length) this.addAtMost(variables, boundedMax, parent);
    if (min > 0) this.addAtMost(variables.map((variable) => -variable), variables.length - min, parent);
  }

  private addAtMost(literals: number[], limit: number, parent?: number): void {
    const addGuardedClause = (clause: number[]): void => {
      this.addClause(parent ? [-parent, ...clause] : clause);
    };
    if (limit < 0) {
      addGuardedClause([]);
      return;
    }
    if (limit >= literals.length) return;
    const width = limit + 1;
    const rows: number[][] = [];
    literals.forEach((literal, index) => {
      const row: number[] = [];
      for (let count = 0; count < width; count++) row.push(this.newAuxiliary());
      rows.push(row);
      addGuardedClause([-literal, row[0]]);
      if (index > 0) {
        const previous = rows[index - 1];
        // Every counter level is monotonic: if the previous prefix already
        // contains `count + 1` selected literals, the current prefix must
        // retain that fact even when the current literal is false.
        this.addClause(parent ? [-parent, -previous[0], row[0]] : [-previous[0], row[0]]);
        for (let count = 1; count < width; count++) {
          addGuardedClause([-previous[count], row[count]]);
          addGuardedClause([-literal, -previous[count - 1], row[count]]);
        }
      }
    });
    const last = rows[rows.length - 1];
    if (last) addGuardedClause([-last[width - 1]]);
  }
}

function solveCnf(clauses: number[][], variableCount: number, options: Required<UvlSolverOptions>): SatResult {
  const started = Date.now();
  const assignment = new Int8Array(variableCount + 1);
  let decisions = 0;
  let propagations = 0;
  let conflicts = 0;
  let timedOut = false;

  const limitReached = (): boolean => {
    if (Date.now() - started > options.maxMillis) {
      timedOut = true;
      return true;
    }
    if (decisions >= options.maxDecisions) {
      timedOut = true;
      return true;
    }
    return false;
  };

  const propagate = (state: Int8Array): boolean => {
    let changed = true;
    while (changed) {
      if (limitReached()) return false;
      changed = false;
      for (const clause of clauses) {
        let unassigned = 0;
        let lastUnassigned = 0;
        let satisfied = false;
        for (const literal of clause) {
          const value = state[Math.abs(literal)];
          if (value === 0) {
            unassigned++;
            lastUnassigned = literal;
          } else if ((literal > 0 && value === 1) || (literal < 0 && value === -1)) {
            satisfied = true;
            break;
          }
        }
        if (satisfied) continue;
        if (unassigned === 0) {
          conflicts++;
          return false;
        }
        if (unassigned === 1) {
          const variable = Math.abs(lastUnassigned);
          const nextValue = lastUnassigned > 0 ? 1 : -1;
          if (state[variable] !== 0 && state[variable] !== nextValue) {
            conflicts++;
            return false;
          }
          if (state[variable] === 0) {
            state[variable] = nextValue;
            propagations++;
            changed = true;
          }
        }
        if (limitReached()) return false;
      }
    }
    return !timedOut;
  };

  const chooseVariable = (state: Int8Array): { variable: number; preferred: number } => {
    const positive = new Int32Array(variableCount + 1);
    const negative = new Int32Array(variableCount + 1);
    const allClausesSatisfied = clauses.every((clause) => clause.some((literal) => {
      const value = state[Math.abs(literal)];
      return (literal > 0 && value === 1) || (literal < 0 && value === -1);
    }));
    if (allClausesSatisfied) return { variable: 0, preferred: 1 };
    clauses.forEach((clause) => {
      const satisfied = clause.some((literal) => {
        const value = state[Math.abs(literal)];
        return (literal > 0 && value === 1) || (literal < 0 && value === -1);
      });
      if (satisfied) return;
      clause.forEach((literal) => {
        if (state[Math.abs(literal)] !== 0) return;
        if (literal > 0) positive[literal]++;
        else negative[-literal]++;
      });
    });
    let best = 0;
    let bestScore = 0;
    let preferred = 1;
    for (let variable = 1; variable <= variableCount; variable++) {
      if (state[variable] !== 0) continue;
      const score = positive[variable] + negative[variable];
      if (score > bestScore) {
        best = variable;
        bestScore = score;
        preferred = positive[variable] >= negative[variable] ? 1 : -1;
      }
    }
    if (best) return { variable: best, preferred };
    for (let variable = 1; variable <= variableCount; variable++) {
      if (state[variable] === 0) return { variable, preferred: 1 };
    }
    return { variable: 0, preferred: 1 };
  };

  const search = (state: Int8Array): { status: "sat" | "unsat" | "unknown"; assignment?: Int8Array } => {
    if (limitReached()) return { status: "unknown" };
    if (!propagate(state)) return { status: timedOut ? "unknown" : "unsat" };
    const choice = chooseVariable(state);
    if (!choice.variable) return { status: "sat", assignment: state };
    if (decisions >= options.maxDecisions) return { status: "unknown" };
    decisions++;
    const first = state.slice();
    first[choice.variable] = choice.preferred;
    const firstResult = search(first);
    if (firstResult.status === "sat" || firstResult.status === "unknown") return firstResult;
    const second = state.slice();
    second[choice.variable] = -choice.preferred;
    return search(second);
  };

  const result = search(assignment);
  return {
    status: result.status,
    assignment: result.assignment,
    decisions,
    propagations,
    conflicts,
    elapsedMs: Date.now() - started,
    reason: result.status === "unknown"
      ? (timedOut ? `SAT analysis limit reached after ${Date.now() - started} ms.` : "SAT analysis limit reached.")
      : undefined,
  };
}

class BddLimitError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "BddLimitError";
  }
}

type BddNode = { variable: number; low: number; high: number };

class BddManager {
  private readonly variableCount: number;
  private readonly maxNodes: number;
  private readonly deadline: number;
  private readonly nodes: BddNode[] = [
    { variable: Number.POSITIVE_INFINITY, low: 0, high: 0 },
    { variable: Number.POSITIVE_INFINITY, low: 1, high: 1 },
  ];
  private readonly unique = new Map<string, number>();
  private readonly applyCache = new Map<string, number>();
  private readonly notCache = new Map<number, number>();

  constructor(variableCount: number, maxNodes: number, deadline = Number.POSITIVE_INFINITY) {
    this.variableCount = variableCount;
    this.maxNodes = maxNodes;
    this.deadline = deadline;
  }

  private checkLimit(): void {
    if (Date.now() > this.deadline) throw new BddLimitError("BDD analysis time limit reached.");
  }

  get nodeCount(): number {
    return this.nodes.length - 2;
  }

  private mk(variable: number, low: number, high: number): number {
    this.checkLimit();
    if (low === high) return low;
    const key = `${variable}|${low}|${high}`;
    const existing = this.unique.get(key);
    if (existing !== undefined) return existing;
    if (this.nodes.length - 2 >= this.maxNodes) throw new BddLimitError(`BDD node limit (${this.maxNodes}) exceeded.`);
    const index = this.nodes.length;
    this.nodes.push({ variable, low, high });
    this.unique.set(key, index);
    return index;
  }

  private variableOf(node: number): number {
    return node < 2 ? Number.POSITIVE_INFINITY : this.nodes[node].variable;
  }

  private cofactor(node: number, variable: number, high: boolean): number {
    if (node < 2 || this.nodes[node].variable !== variable) return node;
    return high ? this.nodes[node].high : this.nodes[node].low;
  }

  private terminalApply(operator: "and" | "or", left: number, right: number): number | undefined {
    if (operator === "and") {
      if (left === 0 || right === 0) return 0;
      if (left === 1) return right;
      if (right === 1) return left;
    } else {
      if (left === 1 || right === 1) return 1;
      if (left === 0) return right;
      if (right === 0) return left;
    }
    if (left === right) return left;
    return undefined;
  }

  apply(operator: "and" | "or", left: number, right: number): number {
    this.checkLimit();
    const terminal = this.terminalApply(operator, left, right);
    if (terminal !== undefined) return terminal;
    const orderedLeft = operator === "and" || operator === "or" ? Math.min(left, right) : left;
    const orderedRight = operator === "and" || operator === "or" ? Math.max(left, right) : right;
    const key = `${operator}|${orderedLeft}|${orderedRight}`;
    const cached = this.applyCache.get(key);
    if (cached !== undefined) return cached;
    const variable = Math.min(this.variableOf(left), this.variableOf(right));
    const low = this.apply(operator, this.cofactor(left, variable, false), this.cofactor(right, variable, false));
    const high = this.apply(operator, this.cofactor(left, variable, true), this.cofactor(right, variable, true));
    const result = this.mk(variable, low, high);
    this.applyCache.set(key, result);
    return result;
  }

  not(node: number): number {
    this.checkLimit();
    if (node === 0) return 1;
    if (node === 1) return 0;
    const cached = this.notCache.get(node);
    if (cached !== undefined) return cached;
    const source = this.nodes[node];
    const result = this.mk(source.variable, this.not(source.low), this.not(source.high));
    this.notCache.set(node, result);
    return result;
  }

  fromFormula(formula: Formula): number {
    if (formula.kind === "constant") return formula.value ? 1 : 0;
    if (formula.kind === "variable") return this.mk(formula.variable, 0, 1);
    if (formula.kind === "not") return this.not(this.fromFormula(formula.operand));
    if (formula.kind === "cardinality") {
      const cardinality = this.fromCardinality(formula.variables, formula.min, formula.max);
      if (formula.parent === undefined) return cardinality;
      return this.apply("or", this.not(this.mk(formula.parent, 0, 1)), cardinality);
    }
    if (formula.kind === "and") return formula.operands.reduce((result, operand) => this.apply("and", result, this.fromFormula(operand)), 1);
    if (formula.kind === "or") return formula.operands.reduce((result, operand) => this.apply("or", result, this.fromFormula(operand)), 0);
    return 0;
  }

  private fromCardinality(variables: number[], min: number, max: number): number {
    const ordered = Array.from(new Set(variables)).sort((left, right) => left - right);
    const boundedMax = Math.min(max, ordered.length);
    const cache = new Map<string, number>();
    const build = (index: number, count: number): number => {
      this.checkLimit();
      if (count > boundedMax) return 0;
      if (index === ordered.length) return count >= min && count <= boundedMax ? 1 : 0;
      const key = `${index}|${count}`;
      const cached = cache.get(key);
      if (cached !== undefined) return cached;
      const variable = ordered[index];
      const low = build(index + 1, count);
      const high = build(index + 1, count + 1);
      const result = this.mk(variable, low, high);
      cache.set(key, result);
      return result;
    };
    if (min < 0 || boundedMax < min) return 0;
    return build(0, 0);
  }

  count(root: number): number {
    const cache = new Map<string, number>();
    const powerOfTwo = (exponent: number): number => {
      if (exponent > 52) return Infinity;
      return 2 ** exponent;
    };
    const countFrom = (node: number, level: number): number => {
      if (node === 0) return 0;
      if (node === 1) return powerOfTwo(this.variableCount - level);
      const key = `${node}|${level}`;
      const cached = cache.get(key);
      if (cached !== undefined) return cached;
      const current = this.nodes[node];
      const skipped = powerOfTwo(current.variable - level);
      const result = skipped * (countFrom(current.low, current.variable + 1) + countFrom(current.high, current.variable + 1));
      cache.set(key, result);
      return result;
    };
    return countFrom(root, 0);
  }

  witness(root: number, names: string[]): Record<string, boolean> | undefined {
    if (root === 0) return undefined;
    const assignment = names.reduce<Record<string, boolean>>((result, name) => {
      result[name] = false;
      return result;
    }, {});
    const find = (node: number, level: number): boolean => {
      if (node === 0) return false;
      if (node === 1) return true;
      const current = this.nodes[node];
      for (let variable = level; variable < current.variable; variable++) assignment[names[variable]] = false;
      if (find(current.low, current.variable + 1)) {
        assignment[names[current.variable]] = false;
        return true;
      }
      if (find(current.high, current.variable + 1)) {
        assignment[names[current.variable]] = true;
        return true;
      }
      return false;
    };
    return find(root, 0) ? assignment : undefined;
  }
}

function buildBdd(formulas: Formula[], featureEntries: FeatureEntry[], options: Required<UvlSolverOptions>): BddResult {
  const started = Date.now();
  try {
    const manager = new BddManager(featureEntries.length, options.maxBddNodes, started + options.maxMillis);
    const root = formulas.reduce((result, formula) => manager.apply("and", result, manager.fromFormula(formula)), 1);
    const status = root === 0 ? "unsat" : "sat";
    const names = featureEntries.map((entry) => entry.displayName);
    return {
      status,
      root,
      model: status === "sat" ? manager.witness(root, names) : undefined,
      modelCount: manager.count(root),
      nodeCount: manager.nodeCount,
      elapsedMs: Date.now() - started,
    };
  } catch (error) {
    return {
      status: "unknown",
      root: 0,
      nodeCount: 0,
      elapsedMs: Date.now() - started,
      reason: error instanceof Error ? error.message : "BDD analysis failed.",
    };
  }
}

function diagnosticDetails(diagnostics: Array<UvlDiagnostic & { sourcePath?: string }>): string[] {
  return diagnostics.slice(0, 8).map((item) => `${item.sourcePath ? `${item.sourcePath}: ` : ""}${locationText(item)}: ${item.message}`);
}

function formatModel(model: Record<string, boolean> | undefined): string {
  if (!model) return "No satisfying configuration was produced.";
  const selected = Object.keys(model).filter((name) => model[name]);
  return selected.length ? `Witness configuration: ${selected.join(", ")}.` : "Witness configuration: no optional features selected.";
}

/**
 * Runs an exact propositional analysis over a composed UVL document.
 *
 * The SAT path uses Tseitin CNF plus a bounded DPLL solver.  The BDD path
 * builds a reduced ordered BDD directly from the same formulas, preserving
 * feature-variable model counts (no Tseitin auxiliary variables are counted).
 * Typed values and arithmetic expressions are reported as UNKNOWN instead of
 * being silently approximated as Boolean values.
 */
export function analyzeUvlWithSolver(
  solver: UvlSolverType,
  source: string,
  submodelSources: UvlSubmodelSources = {},
  rawOptions: UvlSolverOptions = {}
): UvlSolverAnalysisResult {
  const options = { ...DEFAULT_OPTIONS, ...rawOptions };
  const started = Date.now();
  const composition = composeUvlSources(source, submodelSources);
  const baseDetails = [
    `Resolved ${composition.resolvedImports.filter((item) => !item.missing).length} imported submodel(s).`,
    ...diagnosticDetails(composition.warnings),
  ];

  if (!composition.valid) {
    return {
      solver,
      status: "error",
      title: `${solver.toUpperCase()} analysis failed`,
      summary: "The UVL model has structural or semantic errors and cannot be analyzed.",
      details: [...baseDetails, ...diagnosticDetails(composition.errors)],
      elapsedMs: Date.now() - started,
    };
  }

  const compiled = compileDocument(composition.document);
  const featureNames = compiled.featureEntries.map((entry) => entry.displayName);
  const details = [
    `${compiled.featureEntries.length} feature variable(s).`,
    `${compiled.topLevelConstraintCount} top-level constraint(s) plus hierarchy/group constraints.`,
    `BDD variable order: ${featureNames.length ? featureNames.join(", ") : "none"}.`,
    ...baseDetails,
  ];

  if (solver === "sat") {
    const cnf = formulaToCnf(compiled.formulas, compiled.featureEntries, options);
    details.push(`${cnf.clauses.length} CNF clause(s), ${cnf.variableCount} SAT variable(s) (${cnf.auxVariableCount} auxiliary).`);
    if (cnf.reason) {
      return {
        solver,
        status: "unknown",
        title: "SAT analysis incomplete",
        summary: cnf.reason,
        details: [...details, ...compiled.unsupported.map((item) => `Not encoded: ${item}`)],
        featureCount: compiled.featureEntries.length,
        clauseCount: cnf.clauses.length,
        elapsedMs: Date.now() - started,
      };
    }
    const sat = solveCnf(cnf.clauses, cnf.variableCount, options);
    details.push(`DPLL decisions: ${sat.decisions}; propagations: ${sat.propagations}; conflicts: ${sat.conflicts}.`);
    if (sat.reason) details.push(sat.reason);
    if (compiled.unsupported.length) details.push(...compiled.unsupported.map((item) => `Not encoded: ${item}`));
    const exact = compiled.unsupported.length === 0;
    const status: UvlSolverStatus = !exact ? "unknown" : sat.status;
    const model = sat.status === "sat"
      ? featureNames.reduce<Record<string, boolean>>((result, name, index) => {
        result[name] = sat.assignment ? sat.assignment[index + 1] === 1 : false;
        return result;
      }, {})
      : undefined;
    return {
      solver,
      status,
      title: status === "sat" ? "SAT analysis: satisfiable" : status === "unsat" ? "SAT analysis: unsatisfiable" : "SAT analysis: unknown",
      summary: status === "sat"
        ? "A valid feature configuration was found."
        : status === "unsat"
          ? "No feature configuration satisfies all encoded UVL constraints."
          : compiled.unsupported.length
            ? "The Boolean projection was analyzed, but typed UVL semantics prevent an exact SAT result."
            : sat.reason || "The SAT solver reached its configured analysis limit.",
      details: [...details, ...(sat.status === "sat" ? [formatModel(model)] : [])],
      model,
      featureCount: compiled.featureEntries.length,
      clauseCount: cnf.clauses.length,
      elapsedMs: Date.now() - started,
    };
  }

  const bdd = buildBdd(compiled.formulas, compiled.featureEntries, options);
  details.push(`${bdd.nodeCount} reduced BDD decision node(s).`);
  if (bdd.reason) details.push(bdd.reason);
  if (compiled.unsupported.length) details.push(...compiled.unsupported.map((item) => `Not encoded: ${item}`));
  const exact = compiled.unsupported.length === 0;
  const status: UvlSolverStatus = !exact ? "unknown" : bdd.status;
  return {
    solver,
    status,
    title: status === "sat" ? "BDD analysis: satisfiable" : status === "unsat" ? "BDD analysis: unsatisfiable" : "BDD analysis: unknown",
    summary: status === "sat"
      ? `The reduced BDD represents ${bdd.modelCount === Infinity ? "more configurations than can be represented safely" : `${bdd.modelCount} satisfying configuration(s)`}.`
      : status === "unsat"
        ? "The reduced BDD is false; no feature configuration satisfies the model."
        : compiled.unsupported.length
          ? "The Boolean projection was built, but typed UVL semantics prevent an exact BDD result."
          : bdd.reason || "The BDD builder reached its configured analysis limit.",
    details: [...details, ...(bdd.status === "sat" ? [formatModel(bdd.model)] : [])],
    model: bdd.model,
    modelCount: bdd.modelCount,
    featureCount: compiled.featureEntries.length,
    bddNodeCount: bdd.nodeCount,
    elapsedMs: Date.now() - started,
  };
}
